### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by cpyix** [GitHackTools/BillCipher#7]
Hello,
i have this error message while trying to enumerate subdomains:

Process NetcraftEnum-7:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 561, in enumerate
    cookies = self.get_cookies(resp.headers)
  File "sublist3r.py", line 553, in get_cookies
    cookies = self.create_cookies(headers['set-cookie'])
  File "sublist3r.py", line 548, in create_cookies
    cookies['netcraft_js_verification_response'] = hashlib.sha1(urllib.unquote(cookies_list[1])).hexdigest()
TypeError: Unicode-objects must be encoded before hashing

Best regards

**Comment by BaRRaKudaRain** [comment]
Try Python 2?
